### PR TITLE
Fix contributor email links

### LINKED ISSUE #62: Contributor links in recipe docs are not working
## What version of OpenRewrite are you using?

I am using the website [docs.openrewrite.org](https://docs.openrewrite.org/) which mentions it has been last modified 8 days ago. 
Every recipe has a list of `Contributors` at the bottom which the names of the contributors, see [here](https://docs.openrewrite.org/recipes/staticanalysis/commonstaticanalysis). 
This also holds for other pages with contributors.

If I click on any of the contributors (e.g. Tim te Beek) I get redirect to the following page: 
https://github.com/openrewrite/rewrite-docs/blob/master/reference/recipes/staticanalysis/timtebeek@gmail.com
This gives a 404 - page not found, which is probably not the intention of this. 

In the Markdown it shows the following code that is responsible for this:

```md
## Contributors
* [Tim te Beek](tim@moderne.io)
* [Jonathan Schnéider](jkschneider@gmail.com)
```

## What did you expect to see?
To be honest, I'm not 100% sure what the intention is but maybe it should link to person's GitHub page or do something with the email. 

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Depends on what the intent is of the link and how it should be fixed, but probably yes 😄.

### PR DESCRIPTION
**Pull request by timtebeek**
Fixes #62

### CODE REVIEW

File: src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt [hunk 1]
```diff
@@ -1107,7 +1107,11 @@ class RecipeMarkdownGenerator : Runnable {
                 newLine()
                 writeln("## Contributors")
                 for (contributors in recipeDescriptor.contributors) {
-                    writeln("* [${contributors.name}](${contributors.email})")
+                    if (contributors.email.contains("noreply")) {
+                        writeln("* ${contributors.name}")
+                    } else {
+                        writeln("* [${contributors.name}](mailto:${contributors.email})")
+                    }
```
Comment (timtebeek) [inline src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt:1114]: Alternatively we can just always use the name only, or not create mail to links. Up to reviewer.
```suggestion
                    writeln("* ${contributors.name}")
```

Comment (timtebeek) [reply src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt:1114]: Confirmed fixed in https://openrewrite.github.io/rewrite-recipe-markdown-generator/reference/recipes/java/spring/security5/upgradespringsecurity_5_8.html
image
